# Generated by Django 3.2.4 on 2021-06-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filegroup', models.CharField(max_length=100)),
                ('filenum', models.CharField(max_length=100)),
                ('json', models.FileField(upload_to='files/json/')),
            ],
        ),
        migrations.DeleteModel(
            name='ImamgeUpload',
        ),
    ]
