# Generated by Django 3.2.4 on 2021-06-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210610_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='hostname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='protocoll',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
